# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa36ab177e3da5b58d24d68ec94ae82eae7cab6bd3683682bd5813a216685f6bc2aef350ed4cc6843a59395bf4518bbaa7ae8d528d10bbfd05cb20da67e69eb0

test:
  secret_key_base: 0e36cce5c8b5804173d7c706e04e61b51ed56e4c5b28a0f9024fbdfa66ea962e4c1f1ffefcb28113b4ca60381439513e1eec3bba7f13160ce83ad41e9980b93d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
